### ISSUE TITLE
Save As keeps popping up

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Text-Code-Editor#1]
While typing in new code, I get save as dialog that keeps popping up.

The reason is that there is a missing ",".  This statement needed the "," at the end or else it took it to be a single string 'Save' that is being looked INTO.  So if an S or a or v or e is typed, you'll get the popup.  Terribly annoying!

```python
    if event in('Save',):
```

**Comment by israel-dryer** [comment]
ah yes.. forgot about that bit... changing from list to tuple.

**Comment by israel-dryer** [comment]
This is fixed. Although... something else bit me in the ass a few hours ago... and I'll be damned if it wasn't that missing comma somewhere else...
