### ISSUE TITLE
[Request] Run currently visible code, not what's been saved

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Text-Code-Editor#6]
What I like about PyCharm is that I can run the code on my screen at any time.   No need to save as it auto saves.  Regardless, I changed my editor to run the actual code that's in the multiline.  It was a TRIVIAL change.

```python
def run_module(code):
    '''the open script'''
    print(f'Running Session ')
    print('-'*80)
    try:
        exec(code)
    except:
        exec(values['_BODY_']) # need to fix for invalid python code
 
```

and in the while loop

```python
    if event in ('Run Module','F5:116'):
        run_module(values['_BODY_'])
```

**Comment by israel-dryer** [comment]
Ok. I think that's what it does already. The difference I think it's that the original tries to run the saved file first, but if a file hasn't yet been opened, it just runs the code in the multiline. Probably defaulting to the code on the screen as you have it would probably be better though.

**Comment by PySimpleGUI** [comment]
I don't / didn't see any kind of autosave trying to happen when you press F5.  It was just calling the run_module function.
Oh, I see now... I somehow missed the except part entirely.  Sorry!  That was a bad "Fix" I submitted.

**Comment by PySimpleGUI** [comment]
I also think this make the program a little more "legit" that it's running the code you're editing versus launching code contained in a file.

**Comment by israel-dryer** [comment]
No, still good feedback. I think it's a good idea to run what's on the screen as a first response, even if not saved, because that's likely what the user expects. So I will definitely update this piece.

**Comment by israel-dryer** [comment]
This has been implemented.
